### ISSUE TITLE
Unknown Transaction type

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-classic-wallet#1]
![Screenshot_20220906_121512](https://user-images.githubusercontent.com/801414/188720215-ea39d7d2-c420-4492-b0c9-582254474d64.jpg)
![Screenshot_20220906_121552](https://user-images.githubusercontent.com/801414/188720239-e5362543-4974-4559-9887-5e5b6835a2cb.jpg)

9375186853156423439 txn number.

I was accessing as read only mode, on a mobile phone.   Will try same one on Desktop

**Comment by paulpoco** [comment]
Works on Desktop with local Node selected.

Ok mobile I signed as read mode and Europe node

**Comment by deleterium** [comment]
I'm almost sure this is a bad cache on mobile. Touch and hold the reload button for 2 seconds to force download of all files (there are a lot of cached filed in classic wallet). I tested (and worked) in Firefox and Chrome
